### ISSUE TITLE
"assert source" fails

### ISSUE THREAD

**Issue by evgeny-goldin** [melix/codenarc-idea#2]
When I debug Groovy source code and open expression evaluation windows (Alt+F8) I get:

assert source
       |
       java.lang.String@1b355d6: assert source
       |
       java.lang.String@1b355d6
Assertion failed: 

assert source
       |
       java.lang.String@1b355d6

```
at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:378)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:662)
at org.codenarc.source.SourceString.<init>(SourceString.groovy:38)
at org.codenarc.source.SourceString.<init>(SourceString.groovy)
at org.codenarc.idea.CodeNarcInspectionTool$2$1.compute(CodeNarcInspectionTool.java:157)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:45)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:191)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:36)
at org.codenarc.idea.CodeNarcInspectionTool$2.compute(CodeNarcInspectionTool.java:162)
at org.codenarc.idea.CodeNarcInspectionTool$2.compute(CodeNarcInspectionTool.java:150)
at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:52)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:191)
at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
at org.codenarc.idea.CodeNarcInspectionTool.checkFile(CodeNarcInspectionTool.java:185)
at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:128)
at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:76)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:274)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:258)
at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:116)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:114)
at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1016)
at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
at com.intellij.concurrency.JobSchedulerImpl.stealAndRunTask(JobSchedulerImpl.java:65)
at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:126)
at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:258)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:122)
at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1016)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
at com.intellij.concurrency.JobSchedulerImpl.stealAndRunTask(JobSchedulerImpl.java:65)
at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:126)
at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:258)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:122)
at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1016)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:662)
```

assert source
       |
       java.lang.String@15ad940: assert source
       |
       java.lang.String@15ad940
Assertion failed: 

assert source
       |
       java.lang.String@15ad940

```
at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:378)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:662)
at org.codenarc.source.SourceString.<init>(SourceString.groovy:38)
at org.codenarc.source.SourceString.<init>(SourceString.groovy)
at org.codenarc.idea.CodeNarcInspectionTool$2$1.compute(CodeNarcInspectionTool.java:157)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:45)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:191)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:36)
at org.codenarc.idea.CodeNarcInspectionTool$2.compute(CodeNarcInspectionTool.java:162)
at org.codenarc.idea.CodeNarcInspectionTool$2.compute(CodeNarcInspectionTool.java:150)
at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:52)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:191)
at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
at org.codenarc.idea.CodeNarcInspectionTool.checkFile(CodeNarcInspectionTool.java:185)
at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:128)
at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:76)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:274)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:258)
at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:116)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:114)
at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1016)
at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:662)
```

Source code is http://goo.gl/3ONAZ

**Comment by musketyr** [comment]
probably already fixed, feel free to reopen if this still happens
